apiVersion: apps/v1
kind: Deployment
metadata:
  name: osrm-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osrm-backend
  template:
    metadata:
      labels:
        app: osrm-backend
    spec:
        containers:
          - name: osrm-backend
            image: projetomaram/robot-project:osrm-backend
            ports:
              - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: osrm-backend-service
spec:
  selector:
    app: osrm-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: osrm-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osrm-frontend
  template:
    metadata:
      labels:
        app: osrm-frontend
    spec:
        containers:
          - name: osrm-frontend
            image: projetomaram/robot-project:osrm-frontend
            ports:
              - containerPort: 9966
---
apiVersion: v1
kind: Service
metadata:
  name: osrm-frontend-service
spec:
  selector:
    app: osrm-frontend
  ports:
    - protocol: TCP
      port: 9966
      targetPort: 9966
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: osrm-ingress
spec:
  ingressClassName: traefik
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: osrm-frontend-service
            port:
              number: 9966
      - path: /route/v1
        pathType: Prefix
        backend:
          service:
            name: osrm-backend-service
            port:
              number: 5000
